### ISSUE TITLE
AttributeError: module 'bluezero.async_tools' has no attribute 'EventLoop'

### ISSUE THREAD

**Issue by onurcoskun14** [ukBaz/python-bluezero#391] opened 2023-01-23 13:20 UTC
When I try to run cpu_temperature.py I get this error message

Traceback (most recent call last):
  File "/home/pi/deneme.py", line 68, in <module>
    main(list(adapter.Adapter.available())[0].address)
  File "/home/pi/.local/lib/python3.9/site-packages/bluezero/adapter.py", line 55, in available
    yield Adapter(adapter['Address'])
  File "/home/pi/.local/lib/python3.9/site-packages/bluezero/adapter.py", line 86, in __init__
    self.mainloop = async_tools.EventLoop()
AttributeError: module 'bluezero.async_tools' has no attribute 'EventLoop'

**Comment by ukBaz** [comment] 2023-01-23 13:56
I am not able to reproduce this. I've done a test as the following:
```none
$ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
$ systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-12-19 19:26:43 GMT; 1 months 4 days ago
       Docs: man:bluetoothd(8)
   Main PID: 625 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 1598)
        CPU: 1.461s
     CGroup: /system.slice/bluetooth.service
             └─625 /usr/libexec/bluetooth/bluetoothd
$ pip install bluezero
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting bluezero
  Using cached https://www.piwheels.org/simple/bluezero/bluezero-0.7.1-py2.py3-none-any.whl (41 kB)
Installing collected packages: bluezero
Successfully installed bluezero-0.7.1
$ python cpu_temperature.py 
CPU temperature is 42.6°C
Advertisement registered
```

Are you using RPi OS lite or anything like that?
__

**Comment by onurcoskun14** [comment] 2023-01-23 14:20
I'am using Rpi zero w

**Comment by ukBaz** [comment] 2023-01-23 14:52
Being on a RPi Zero W shouldn't be a problem.   

Did `systemctl status bluetooth` work for you?
Does running `bluetoothctl show` on the command line work?

Should give you somwthing like:
```none
$ bluetoothctl show
Controller B8:27:EB:22:57:E0 (public)
        Name: SensePi
        Alias: SensePi
        Class: 0x002c0000
        Powered: yes
        Discoverable: no
        DiscoverableTimeout: 0x000000b4
        Pairable: no
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: Audio Source              (0000110a-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
        UUID: Headset                   (00001108-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Headset AG                (00001112-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0537
        Discovering: no
        Roles: central
        Roles: peripheral
Advertising Features:
        ActiveInstances: 0x00 (0)
        SupportedInstances: 0x05 (5)
        SupportedIncludes: tx-power
        SupportedIncludes: appearance
        SupportedIncludes: local-name
```

**Comment by onurcoskun14** [comment] 2023-01-24 12:14
![image](https://user-images.githubusercontent.com/117642438/214285163-89d54662-62a5-4e61-aff7-156519a7ab49.png)

It seems okey

**Comment by onurcoskun14** [comment] 2023-01-24 12:18
![image](https://user-images.githubusercontent.com/117642438/214289070-f40be773-8b36-4f2a-9687-05c0e9fa4feb.png)

![image](https://user-images.githubusercontent.com/117642438/214289582-3a61e483-0e15-4e41-a4a9-c54499b44f8a.png)

I couldn't solve the Failed to set privacy error

**Comment by onurcoskun14** [comment] 2023-01-27 11:24
By the way I'am using OS Lite is that a problem ?

**Comment by ukBaz** [comment] 2023-01-27 11:39
> By the way I'am using OS Lite is that a problem ?

Not a problem, no.   I haven't stayed up to date with the changes on OS Lite, but there has historically been some extra steps that are needed. e.g. https://raspberrypi.stackexchange.com/a/116843/121848

The most worrying of what you've shown is the `--compat` option.  

The issues you have are system specific and seem to be a result of you customising your system. This means it is not Bluezero specific and are difficult to diagnose without access to your system. I think this means it is going to be difficult for me to help you.

**Comment by onurcoskun14** [comment] 2023-01-27 12:41
I have installed RPİ OS Full and it works now. OS Lite might be the problem.
![image](https://user-images.githubusercontent.com/117642438/215089547-5d7de36c-abdc-4b9c-8642-6dfe5be6739e.png)
this one from OS Lite

----------------------------

![image](https://user-images.githubusercontent.com/117642438/215089670-a1822ee6-3351-4238-a633-f96ec4e07077.png)
This one from OS Full

**Comment by ukBaz** [comment] 2023-01-27 13:15
Thanks for letting me know the update. Good news.

I'll go ahead and close this.

**Closed by ukBaz** 2023-01-27 13:15 UTC
